/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 room_pointlight.glb -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.Mesh
    Cube001: THREE.Mesh
    Cube002: THREE.Mesh
  }
  materials: {
    Material: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[];
}

export function Store_1(props: React.JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/3d_assets/room_pointlight.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <PerspectiveCamera makeDefault={true} far={1000} near={0.1} fov={25} position={[0, 4, 13]}  />
      <pointLight intensity={50} decay={2} position={[0, 5.981, 0]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.003']} position={[-0.686, 4.145, -2.806]} scale={[1.554, 1.177, 0.077]} receiveShadow/>
      <mesh geometry={nodes.Cube002.geometry} material={materials['Material.001']} position={[-0.686, 1.2, -1.973]} scale={[1.554, 1.177, 0.582]} receiveShadow/>
    </group>
  )
}

useGLTF.preload('/3d_assets/room_pointlight.glb')
