spring.profiles.active=local
spring.application.name=core
spring.datasource.driver-class-name=org.postgresql.Driver
hibernate.hbm2ddl.auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.graphql.graphiql.enabled=true
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.ca-central-1.amazonaws.com/ca-central-1_Sow0DGQST