type Query {
    me: User
    user(id: ID!): User
    album(id: ID!): Album
    albums: [Album!]!
    track(id: ID!): Track
}

type Mutation {
    createAlbum(title: String!, artist: String): Album!
    updateAlbum(id: ID!, title: String, artist: String): Album!
    deleteAlbum(id: ID!): Boolean!

    createTrack(
        albumId: ID!
        title: String!
        trackNo: Int
        duration: Float
    ): Track!

    updateTrack(
        id: ID!
        title: String
        trackNo: Int
        duration: Float
    ): Track!

    deleteTrack(id: ID!): Boolean!
}

type User {
    id: ID!
    username: String!
    email: String!
    createdAt: String!
    updatedAt: String!

    albums: [Album!]!
}

type Album {
    id: ID!
    userId: ID!

    title: String!
    artist: String
    coverUrl: String

    createdAt: String!
    updatedAt: String!

    user: User!
    tracks: [Track!]!
}

type Track {
    id: ID!
    albumId: ID!

    title: String!
    trackNo: Int
    duration: Float

    audioUrl: String
    originalAudioUrl: String

    createdAt: String!
    updatedAt: String!

    album: Album!
}

